// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	billing "encore.app/fees/internal/store/billing"
	mock "github.com/stretchr/testify/mock"
)

// ActivityStore is an autogenerated mock type for the ActivityStore type
type ActivityStore struct {
	mock.Mock
}

// FinalizeBill provides a mock function with given fields: ctx, billID
func (_m *ActivityStore) FinalizeBill(ctx context.Context, billID string) (*billing.FinalizeBillResult, error) {
	ret := _m.Called(ctx, billID)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeBill")
	}

	var r0 *billing.FinalizeBillResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*billing.FinalizeBillResult, error)); ok {
		return rf(ctx, billID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.FinalizeBillResult); ok {
		r0 = rf(ctx, billID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.FinalizeBillResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, billID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertLineItems provides a mock function with given fields: ctx, params
func (_m *ActivityStore) InsertLineItems(ctx context.Context, params billing.InsertLineItemsParams) (*billing.InsertLineItemsResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InsertLineItems")
	}

	var r0 *billing.InsertLineItemsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, billing.InsertLineItemsParams) (*billing.InsertLineItemsResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, billing.InsertLineItemsParams) *billing.InsertLineItemsResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.InsertLineItemsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, billing.InsertLineItemsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBill provides a mock function with given fields: ctx, params
func (_m *ActivityStore) UpdateBill(ctx context.Context, params billing.UpdateBillParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, billing.UpdateBillParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewActivityStore creates a new instance of ActivityStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityStore {
	mock := &ActivityStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
