// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "encore.app/fees/internal/domain"
	billing "encore.app/fees/internal/store/billing"
	mock "github.com/stretchr/testify/mock"
)

// BillingStore is an autogenerated mock type for the Store type
type BillingStore struct {
	mock.Mock
}

// GetBill provides a mock function with given fields: ctx, billID
func (_m *BillingStore) GetBill(ctx context.Context, billID string) (*domain.Bill, error) {
	ret := _m.Called(ctx, billID)

	if len(ret) == 0 {
		panic("no return value specified for GetBill")
	}

	var r0 *domain.Bill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Bill, error)); ok {
		return rf(ctx, billID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Bill); ok {
		r0 = rf(ctx, billID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Bill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, billID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertBill provides a mock function with given fields: ctx, params
func (_m *BillingStore) InsertBill(ctx context.Context, params billing.InsertBillParams) (*billing.InsertBillResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InsertBill")
	}

	var r0 *billing.InsertBillResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, billing.InsertBillParams) (*billing.InsertBillResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, billing.InsertBillParams) *billing.InsertBillResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.InsertBillResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, billing.InsertBillParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertLineItems provides a mock function with given fields: ctx, params
func (_m *BillingStore) InsertLineItems(ctx context.Context, params billing.InsertLineItemsParams) (*billing.InsertLineItemsResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InsertLineItems")
	}

	var r0 *billing.InsertLineItemsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, billing.InsertLineItemsParams) (*billing.InsertLineItemsResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, billing.InsertLineItemsParams) *billing.InsertLineItemsResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.InsertLineItemsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, billing.InsertLineItemsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLineItems provides a mock function with given fields: ctx, params
func (_m *BillingStore) ListLineItems(ctx context.Context, params billing.ListLineItemsParams) (*billing.ListLineItemsResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListLineItems")
	}

	var r0 *billing.ListLineItemsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, billing.ListLineItemsParams) (*billing.ListLineItemsResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, billing.ListLineItemsParams) *billing.ListLineItemsResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.ListLineItemsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, billing.ListLineItemsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBill provides a mock function with given fields: ctx, params
func (_m *BillingStore) UpdateBill(ctx context.Context, params billing.UpdateBillParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, billing.UpdateBillParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBillingStore creates a new instance of BillingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillingStore {
	mock := &BillingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
