// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	idempotency "encore.app/fees/internal/store/idempotency"
	mock "github.com/stretchr/testify/mock"
)

// IdempotencyStore is an autogenerated mock type for the Store type
type IdempotencyStore struct {
	mock.Mock
}

// Complete provides a mock function with given fields: ctx, params
func (_m *IdempotencyStore) Complete(ctx context.Context, params idempotency.CompleteParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, idempotency.CompleteParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reserve provides a mock function with given fields: ctx, params
func (_m *IdempotencyStore) Reserve(ctx context.Context, params idempotency.ReserveParams) (*idempotency.ReserveResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 *idempotency.ReserveResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, idempotency.ReserveParams) (*idempotency.ReserveResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, idempotency.ReserveParams) *idempotency.ReserveResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idempotency.ReserveResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, idempotency.ReserveParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIdempotencyStore creates a new instance of IdempotencyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdempotencyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdempotencyStore {
	mock := &IdempotencyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
