// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	workflow "encore.app/fees/internal/workflow"
	mock "github.com/stretchr/testify/mock"
)

// WorkflowClient is an autogenerated mock type for the Client type
type WorkflowClient struct {
	mock.Mock
}

// AddLineItems provides a mock function with given fields: ctx, billID, input
func (_m *WorkflowClient) AddLineItems(ctx context.Context, billID string, input workflow.AddLineItemsInput) (*workflow.AddLineItemsResult, error) {
	ret := _m.Called(ctx, billID, input)

	if len(ret) == 0 {
		panic("no return value specified for AddLineItems")
	}

	var r0 *workflow.AddLineItemsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, workflow.AddLineItemsInput) (*workflow.AddLineItemsResult, error)); ok {
		return rf(ctx, billID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, workflow.AddLineItemsInput) *workflow.AddLineItemsResult); ok {
		r0 = rf(ctx, billID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.AddLineItemsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, workflow.AddLineItemsInput) error); ok {
		r1 = rf(ctx, billID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CloseBill provides a mock function with given fields: ctx, billID, input
func (_m *WorkflowClient) CloseBill(ctx context.Context, billID string, input workflow.CloseBillInput) (*workflow.CloseBillResult, error) {
	ret := _m.Called(ctx, billID, input)

	if len(ret) == 0 {
		panic("no return value specified for CloseBill")
	}

	var r0 *workflow.CloseBillResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, workflow.CloseBillInput) (*workflow.CloseBillResult, error)); ok {
		return rf(ctx, billID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, workflow.CloseBillInput) *workflow.CloseBillResult); ok {
		r0 = rf(ctx, billID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.CloseBillResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, workflow.CloseBillInput) error); ok {
		r1 = rf(ctx, billID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetState provides a mock function with given fields: ctx, billID
func (_m *WorkflowClient) GetState(ctx context.Context, billID string) (*workflow.State, error) {
	ret := _m.Called(ctx, billID)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 *workflow.State
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*workflow.State, error)); ok {
		return rf(ctx, billID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *workflow.State); ok {
		r0 = rf(ctx, billID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.State)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, billID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartBillWorkflow provides a mock function with given fields: ctx, input
func (_m *WorkflowClient) StartBillWorkflow(ctx context.Context, input workflow.StartBillWorkflowInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for StartBillWorkflow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, workflow.StartBillWorkflowInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorkflowClient creates a new instance of WorkflowClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkflowClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkflowClient {
	mock := &WorkflowClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
